sudo: required
language: node_js
node_js:
  - 8
services:
  - docker
cache:
  directories:
    - node_modules

before_install:
  - docker build -t wheresmycookie/frontend:test -f Dockerfile.dev .

script:
  - echo "Tests finished successfully..."

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-955816401101"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
