sudo: required
language: node_js
node_js:
  - 8
services:
  - docker
cache:
  directories:
    - node_modules

before_install:
  - docker build -t wheresmycookie/frontend:test -f Dockerfile.dev .

script:
  - echo "Tests finished successfully..."
